import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/Nav";
import Header from "@/components/Header";
import Support from "@/components/Support";
import Footer from "@/components/Footer";
import Layout from "@/components/Layout";
import { Work_Sans } from 'next/font/google';

const workSans = Work_Sans({
  subsets: ['latin'],
  variable: '--font-work-sans',
  weight: ['400', '500', '700'],
});

export const metadata: Metadata = {
  title: "Courthouse Computer Systems",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {


  return (
    <html lang="en">
      <body
        className={`${workSans.variable} antialiased flex flex-col min-h-screen`}
      >
        <Header/>
        <Nav/>
        <Support/>
          <Layout>{children}</Layout>
        <Footer/>
      </body>
    </html>
  );
}
